name: ci

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run test:unit
      - run: npm run package:vsix
        if: github.event_name == 'pull_request' && github.event.action == 'ready_for_review'
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request' && github.event.action == 'ready_for_review'
        with:
          name: rmd-notebooks-vsix
          path: "*.vsix"
